### ISSUE TITLE
The system cannot find specified path

### ISSUE THREAD

**Issue by papano24** [horacio9a/streamate-anonymous#4]
Warning, just let you know that I am new to this. Having an issue with getting this to run properly. I was able to install all the components. I placed the ffmpeg. rtmpdump, ffplay and livestreamer plugins in the streamate folder. However, when I run the sm.bat and select a model it keeps popping up "the system cannot find the path specified". I checked the config.cfg and it shows everything placed properly. It does appear that I am having some difficulty with the python files. I see that you have everything setup for python 2.7, but I have the 3.6.2 version. Would that cause an issue? Below are the error messages that I receive when trying to run the python scripts:

C:\streamate-anonymous-master>python sm.py
  File "sm.py", line 22
    print ' =>',(num+1),value[:-1]
              ^
SyntaxError: invalid syntax

C:\streamate-anonymous-master>python smls.py
Traceback (most recent call last):
  File "smls.py", line 3, in <module>
    import sys, os, urllib, requests, json, ssl, re, time, datetime, command
ModuleNotFoundError: No module named 'command'

C:\streamate-anonymous-master>python smff.py
  File "smff.py", line 19
    print ' =>',(num+1),value[:-1]
              ^
SyntaxError: invalid syntax

C:\streamate-anonymous-master>python smffr.py
Traceback (most recent call last):
  File "smffr.py", line 3, in <module>
    import sys, os, urllib, requests, json, ssl, re, time, datetime, command
ModuleNotFoundError: No module named 'command'

C:\streamate-anonymous-master>python smr.py
Traceback (most recent call last):
  File "smr.py", line 3, in <module>
    import sys, os, urllib, urllib3, ssl, re, time, datetime, command
ModuleNotFoundError: No module named 'command'

**Comment by horacio9a** [comment]
You should install Python 2.7.14 (Links is https://www.python.org/downloads/windows/ , https://www.python.org/ftp/python/2.7.14/python-2.7.14.msi  ) in C:\Python27 directory.
You can keep your Python 3.6.2 installation in C:\Python36 directory. Watch this video: https://www.youtube.com/watch?v=QYUBz4mrnFU ... at the end you can see how to edit your windows path. With editing path you can choose between Python27 or Python36.

... ;C:\Python27\;C:\Python27\Scripts\; ...
or
... ;C:\Python36\;C:\Python36\Scripts\; ...

**Comment by papano24** [comment]
Update------ 
I was able to get farther this go round. I installed python 2.7 and edited the environment variables. I noticed that the requirements.txt does not install all the components as it stalls when collecting for urllib==1.21.1.  (error message below). The other components in the txt. file I had to install each separately.  After installation, I ran each python script via command line(log below) and it was not able to record any model. I even tried the sm.bat and selected each option and received a message stating "The system cannot find the path specified." Is this due to the "urllib==1.21.1" not bring installed. Looking forward to your feedback.

**urllib error**
Collecting urllib==1.21.1
  Could not find a version that satisfies the requirement urllib==1.21.1 (from v
ersions: )
No matching distribution found for urllib==1.21.1

**Command Line Logs**
C:\Users\admin>cd C:\streamate-anonymous-master

C:\streamate-anonymous-master>python sm.py
 => START <=

 => 1 BigtitsVSBIGcock
 => 2 bic_cock_girlmilk4u
 => 3 CoupleHotDirty
 => 4 AminaField

 => Select SM Model => 4

 => Selected SM Model => AminaField <=

Traceback (most recent call last):
  File "sm.py", line 41, in <module>
    sid0 = dec.split("p_sid: '")[1]
IndexError: list index out of range

C:\streamate-anonymous-master>python smff.py
 => START <=

 => 1 BigtitsVSBIGcock
 => 2 bic_cock_girlmilk4u
 => 3 CoupleHotDirty
 => 4 AminaField

 => Select SM Model => 4

 => Selected SM Model => AminaField <=

Traceback (most recent call last):
  File "smff.py", line 37, in <module>
    modelinfo['stream']['streamId'] + "&sakey=&sessiontype=preview&perfdiscounti
d=0&minduration=0&goldshowid=0&version=7&referrer=hybrid.client.2.3.1%2Favchat.s
wf&usertype=false&EIO=3&transport=websocket"
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

C:\streamate-anonymous-master>python smffr.py
 => START <=

Traceback (most recent call last):
  File "smffr.py", line 17, in <module>
    model = sys.argv[1]
IndexError: list index out of range

C:\streamate-anonymous-master>python smls.py

 => START <=

 => 1 BigtitsVSBIGcock
 => 2 bic_cock_girlmilk4u
 => 3 CoupleHotDirty
 => 4 AminaField

 => Select SM Model => 4

 => Selected SM Model => AminaField <=

Traceback (most recent call last):
  File "smls.py", line 39, in <module>
    modelinfo['stream']['streamId'] + "&sakey=&sessiontype=preview&perfdiscounti
d=0&minduration=0&goldshowid=0&version=7&referrer=hybrid.client.2.3.1%2Favchat.s
wf&usertype=false&EIO=3&transport=websocket"
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

C:\streamate-anonymous-master>python smlsr.py
 => START <=

Traceback (most recent call last):
  File "smlsr.py", line 17, in <module>
    model = sys.argv[1]
IndexError: list index out of range

C:\streamate-anonymous-master>python smr.py
 => START <=

Traceback (most recent call last):
  File "smr.py", line 20, in <module>
    model = sys.argv[1]
IndexError: list index out of range

**Comment by horacio9a** [comment]
The so-called 'remote' scripts (scripts ending with the letter 'r') should start in the following way:

python smffr.py (**model name**)

It is therefore best to use a batch script '**sm.bat**' to run python scripts.

I made some minor changes to '**sm.py**' and here's how it looks now:

![2609](https://user-images.githubusercontent.com/17076459/33940727-6e5db248-e010-11e7-8d7c-b07af31b778a.jpg)

**Comment by papano24** [comment]
Aight, looks like it is good to go. Thanks for the quick responses. Quick question tho, do you think for future ones you will create a UI and possibly allow for tracking?
